inherit_gem:
  decidim-dev: rubocop-decidim.yml

AllCops:
  Exclude:
    - "spec/decidim_dummy_app*/**/*"
    - "db/**/*.rb"
    - "vendor/**/*"
    - "development_app/**/*.rb"
    - "development_app/Gemfile"

Rails/FilePath:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
